DOMAIN = "energy_arbitrage"

CONF_PV_POWER_SENSOR = "pv_power_sensor"
CONF_PV_FORECAST_TODAY_SENSOR = "pv_forecast_today_sensor"
CONF_PV_FORECAST_TOMORROW_SENSOR = "pv_forecast_tomorrow_sensor"
CONF_BATTERY_LEVEL_SENSOR = "battery_level_sensor"
CONF_BATTERY_POWER_SENSOR = "battery_power_sensor"
CONF_LOAD_POWER_SENSOR = "load_power_sensor"
CONF_GRID_POWER_SENSOR = "grid_power_sensor"
CONF_WORK_MODE_SELECT = "work_mode_select"
CONF_BATTERY_GRID_CHARGING_SWITCH = "battery_grid_charging_switch"
CONF_TODAY_BATTERY_CYCLES_SENSOR = "today_battery_cycles_sensor"
CONF_TOTAL_BATTERY_CYCLES_SENSOR = "total_battery_cycles_sensor"
CONF_MQTT_BUY_TOPIC = "mqtt_buy_topic"
CONF_MQTT_SELL_TOPIC = "mqtt_sell_topic"

CONF_MAX_PV_POWER = "max_pv_power"
CONF_BATTERY_CAPACITY = "battery_capacity"
CONF_MIN_BATTERY_RESERVE = "min_battery_reserve"
CONF_BATTERY_EFFICIENCY = "battery_efficiency"
CONF_MAX_BATTERY_POWER = "max_battery_power"
CONF_PLANNING_HORIZON = "planning_horizon"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_MIN_ARBITRAGE_MARGIN = "min_arbitrage_margin"
CONF_SELF_CONSUMPTION_PRIORITY = "self_consumption_priority"

CONF_BATTERY_COST = "battery_cost"
CONF_BATTERY_CYCLES = "battery_cycles"
CONF_INCLUDE_DEGRADATION = "include_degradation"
CONF_MAX_DAILY_CYCLES = "max_daily_cycles"
CONF_MIN_ARBITRAGE_DEPTH = "min_arbitrage_depth"
CONF_DEGRADATION_FACTOR = "degradation_factor"
CONF_CURRENCY = "currency"

DEFAULT_MAX_PV_POWER = 10.6
DEFAULT_BATTERY_CAPACITY = 15.0
DEFAULT_MIN_BATTERY_RESERVE = 20
DEFAULT_BATTERY_EFFICIENCY = 90
DEFAULT_MAX_BATTERY_POWER = 5.0
DEFAULT_PLANNING_HORIZON = 24
DEFAULT_UPDATE_INTERVAL = 15
DEFAULT_MIN_ARBITRAGE_MARGIN = 5
DEFAULT_SELF_CONSUMPTION_PRIORITY = True

DEFAULT_BATTERY_COST = 8000
DEFAULT_BATTERY_CYCLES = 6000
DEFAULT_INCLUDE_DEGRADATION = True
DEFAULT_MAX_DAILY_CYCLES = 2.0
DEFAULT_MIN_ARBITRAGE_DEPTH = 40
DEFAULT_DEGRADATION_FACTOR = 1.0
DEFAULT_CURRENCY = "PLN"

WORK_MODE_EXPORT_FIRST = "Export First"
WORK_MODE_ZERO_EXPORT = "Zero Export To Load"

UPDATE_INTERVAL_SECONDS = 900